name: CI
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:  
    - uses: actions/checkout@v2
    - name: Setup tmate sessionss
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
    
